### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by JIzabal** [jupoon/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
  - Missing tests and expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
  - Missing tests and expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
  - Missing tests and expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by JIzabal** [comment]
The expected output for `testSnippet3` should only be one url. Use [this](https://spec.commonmark.org/dingus/) to input snippet 3 to see the one highlighted link that should be part of the expected output. Also, please answer each of the code change questions more in depth, because currently your answer only talks about how to fix your errors. Please also separate the answers by each question. Once you do that, respond here so I can check.

**Comment by jupoon-other** [comment]
I believe I have fixed all the problems with my lab report 4. Here is the link to my lab report page: https://jupoon.github.io/cse15l-lab-reports/labs/lab4/lab-report-4

**Comment by JIzabal** [comment]
Nice work!
